[2025-07-17T07:02:04.943+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: quant_backtest.ingest_data scheduled__2023-07-30T00:00:00+00:00 [queued]>
[2025-07-17T07:02:04.948+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: quant_backtest.ingest_data scheduled__2023-07-30T00:00:00+00:00 [queued]>
[2025-07-17T07:02:04.948+0000] {taskinstance.py:1308} INFO - Starting attempt 2 of 6
[2025-07-17T07:02:04.955+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): ingest_data> on 2023-07-30 00:00:00+00:00
[2025-07-17T07:02:04.958+0000] {standard_task_runner.py:57} INFO - Started process 225 to run task
[2025-07-17T07:02:04.960+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'quant_backtest', 'ingest_data', 'scheduled__2023-07-30T00:00:00+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/quant_backtest.py', '--cfg-path', '/tmp/tmplx7uvgfc']
[2025-07-17T07:02:04.961+0000] {standard_task_runner.py:85} INFO - Job 78: Subtask ingest_data
[2025-07-17T07:02:04.993+0000] {task_command.py:410} INFO - Running <TaskInstance: quant_backtest.ingest_data scheduled__2023-07-30T00:00:00+00:00 [running]> on host 4c28034d5b9c
[2025-07-17T07:02:05.050+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='quant_backtest' AIRFLOW_CTX_TASK_ID='ingest_data' AIRFLOW_CTX_EXECUTION_DATE='2023-07-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-30T00:00:00+00:00'
[2025-07-17T07:02:05.053+0000] {logging_mixin.py:150} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/utils/context.py:313 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-07-17T07:02:05.053+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/quant_backtest.py", line 37, in ingest
    df = fetch_data('AAPL', d, d)
NameError: name 'fetch_data' is not defined
[2025-07-17T07:02:05.060+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=quant_backtest, task_id=ingest_data, execution_date=20230730T000000, start_date=20250717T070204, end_date=20250717T070205
[2025-07-17T07:02:05.066+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 78 for task ingest_data (name 'fetch_data' is not defined; 225)
[2025-07-17T07:02:05.101+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-07-17T07:02:05.118+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
