[2025-07-18T01:56:43.994+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: quant_backtest.ingest_data scheduled__2023-07-30T00:00:00+00:00 [queued]>
[2025-07-18T01:56:43.998+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: quant_backtest.ingest_data scheduled__2023-07-30T00:00:00+00:00 [queued]>
[2025-07-18T01:56:43.998+0000] {taskinstance.py:1308} INFO - Starting attempt 6 of 6
[2025-07-18T01:56:44.006+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): ingest_data> on 2023-07-30 00:00:00+00:00
[2025-07-18T01:56:44.009+0000] {standard_task_runner.py:57} INFO - Started process 220 to run task
[2025-07-18T01:56:44.011+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'quant_backtest', 'ingest_data', 'scheduled__2023-07-30T00:00:00+00:00', '--job-id', '94', '--raw', '--subdir', 'DAGS_FOLDER/quant_backtest.py', '--cfg-path', '/tmp/tmpgx4hvuuq']
[2025-07-18T01:56:44.012+0000] {standard_task_runner.py:85} INFO - Job 94: Subtask ingest_data
[2025-07-18T01:56:44.042+0000] {task_command.py:410} INFO - Running <TaskInstance: quant_backtest.ingest_data scheduled__2023-07-30T00:00:00+00:00 [running]> on host d28433d33c7b
[2025-07-18T01:56:44.105+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='quant_backtest' AIRFLOW_CTX_TASK_ID='ingest_data' AIRFLOW_CTX_EXECUTION_DATE='2023-07-30T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='6' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-30T00:00:00+00:00'
[2025-07-18T01:56:44.109+0000] {logging_mixin.py:150} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/utils/context.py:313 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-07-18T01:56:44.109+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/quant_backtest.py", line 37, in ingest
    df = fetch_data('AAPL', d, d)
NameError: name 'fetch_data' is not defined
[2025-07-18T01:56:44.117+0000] {taskinstance.py:1350} INFO - Marking task as FAILED. dag_id=quant_backtest, task_id=ingest_data, execution_date=20230730T000000, start_date=20250718T015643, end_date=20250718T015644
[2025-07-18T01:56:44.123+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 94 for task ingest_data (name 'fetch_data' is not defined; 220)
[2025-07-18T01:56:44.151+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-07-18T01:56:44.167+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
