[2025-07-17T06:44:58.422+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: quant_backtest.ingest_data scheduled__2023-07-29T00:00:00+00:00 [queued]>
[2025-07-17T06:44:58.427+0000] {taskinstance.py:1103} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: quant_backtest.ingest_data scheduled__2023-07-29T00:00:00+00:00 [queued]>
[2025-07-17T06:44:58.427+0000] {taskinstance.py:1308} INFO - Starting attempt 1 of 2
[2025-07-17T06:44:58.435+0000] {taskinstance.py:1327} INFO - Executing <Task(PythonOperator): ingest_data> on 2023-07-29 00:00:00+00:00
[2025-07-17T06:44:58.439+0000] {standard_task_runner.py:57} INFO - Started process 246 to run task
[2025-07-17T06:44:58.440+0000] {standard_task_runner.py:84} INFO - Running: ['airflow', 'tasks', 'run', 'quant_backtest', 'ingest_data', 'scheduled__2023-07-29T00:00:00+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/quant_backtest.py', '--cfg-path', '/tmp/tmpatk0et1v']
[2025-07-17T06:44:58.442+0000] {standard_task_runner.py:85} INFO - Job 72: Subtask ingest_data
[2025-07-17T06:44:58.472+0000] {task_command.py:410} INFO - Running <TaskInstance: quant_backtest.ingest_data scheduled__2023-07-29T00:00:00+00:00 [running]> on host 24ebc2bdd9e4
[2025-07-17T06:44:58.529+0000] {taskinstance.py:1547} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='you' AIRFLOW_CTX_DAG_ID='quant_backtest' AIRFLOW_CTX_TASK_ID='ingest_data' AIRFLOW_CTX_EXECUTION_DATE='2023-07-29T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-07-29T00:00:00+00:00'
[2025-07-17T06:44:58.532+0000] {logging_mixin.py:150} WARNING - /home/airflow/.local/lib/python3.7/site-packages/airflow/utils/context.py:313 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2025-07-17T06:44:58.864+0000] {taskinstance.py:1824} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 181, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 198, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/quant_backtest.py", line 32, in ingest
    fetch_agg_bars('AAPL', d, d)
  File "/opt/airflow/data_ingestion/ingestion.py", line 28, in fetch_agg_bars
    r.raise_for_status()
  File "/home/airflow/.local/lib/python3.7/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 429 Client Error: Too Many Requests for url: https://api.polygon.io/v2/aggs/ticker/AAPL/range/1/minute/2023-07-29/2023-07-29?adjusted=true&sort=asc&limit=5000&apiKey=XbTx7h_kP0dGxI8fdRCC7Blx9i0Wjr3l
[2025-07-17T06:44:58.871+0000] {taskinstance.py:1350} INFO - Marking task as UP_FOR_RETRY. dag_id=quant_backtest, task_id=ingest_data, execution_date=20230729T000000, start_date=20250717T064458, end_date=20250717T064458
[2025-07-17T06:44:58.878+0000] {standard_task_runner.py:109} ERROR - Failed to execute job 72 for task ingest_data (429 Client Error: Too Many Requests for url: https://api.polygon.io/v2/aggs/ticker/AAPL/range/1/minute/2023-07-29/2023-07-29?adjusted=true&sort=asc&limit=5000&apiKey=XbTx7h_kP0dGxI8fdRCC7Blx9i0Wjr3l; 246)
[2025-07-17T06:44:58.926+0000] {local_task_job_runner.py:225} INFO - Task exited with return code 1
[2025-07-17T06:44:58.941+0000] {taskinstance.py:2653} INFO - 0 downstream tasks scheduled from follow-on schedule check
